
name: YunoHost App CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linter
        run: pip install yunohost-app-ci
      - name: Run linter
        run: yunohost-app-ci lint .

  install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run install tests
        uses: YunoHost/apps_testing@v1
        with:
          package: .
          testfile: tests/tests.toml
